sudo: false
language: rust
matrix:
  fast_finish: true
  allow_failures:
    - name: rust beta
    - name: rust nightly
    - name: coverage
  include:
    - name: rust stable
      rust: stable

    - name: rust beta
      rust: beta

    - name: rust nightly
      rust: nightly

    - name: fmt
      rust: stable
      install:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --check

    # - name: warnings
    #   rust: stable
    #   env: RUSTFLAGS="-D warnings"
    #   script:
    #     - cargo check --tests

    - name: clippy
      rust: stable
      install:
        - rustup component add clippy-preview
      script:
        - cargo clippy -- -D clippy

    - name: coverage
      rust: stable
      script: |
        curl https://github.com/SimonKagstrom/kcov/archive/master.tar.gz | tar xvz &&
        cd kcov-master &&
        cmake . &&
        make -j &&
        cd .. &&
        export PATH=$PWD/bin &&
        cargo test --features kcov -- --test-threads 1 &&
        bash <(curl -s https://codecov.io/bash) &&
        echo "Uploaded code coverage"
      addons: # required for kcov
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - cmake

script:
- cargo test --verbose

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

cache:
  apt: true
  cargo: true
before_cache:
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never